### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Foxti22** [RitaSister/DonateCase#3]
### Server Implementation

Paper

### Server Version

1.14.4

### Describe the bug

[15:00:42 ERROR]: Could not load 'plugins\DonateCase.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: net/ritasister/dc/DonateCase has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0.

Помогите, вот такая ошибка!

### To Reproduce

1. Перекинул плагин себе в папку.
2. Запустил сервер
3. Высветилась ошибка

### Expected behaviour

Удачный запуск плагина

### DonateCase version

0.1.6

### Checklist

- [X] I am using the newest build from https://github.com/RitaSister/ServerRegionProtect/releases/ and the issue still persists.

**Comment by Foxti22** [comment]
@RitaSister помоги

**Comment by RitaSister** [comment]
эта версия не поддерживается из-за компиляции джавы. Надо будет скомпилировать под другую версию или можешь сам из исходников.
